/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { default as DecreaseScriptJson } from "../Decrease.ral.json";
import { default as IncreaseScriptJson } from "../Increase.ral.json";

export const Decrease = new ExecutableScript<{
  counter: HexString;
  num: bigint;
  to: Address;
}>(Script.fromJson(DecreaseScriptJson));
export const Increase = new ExecutableScript<{
  counter: HexString;
  num: bigint;
}>(Script.fromJson(IncreaseScriptJson));
