/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { default as AddScriptJson } from "../Add.ral.json";

export const Add = new ExecutableScript<{ counter: HexString; num: bigint }>(
  Script.fromJson(AddScriptJson)
);
