/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { default as ConsumeScriptJson } from "../Consume.ral.json";
import { default as ProduceScriptJson } from "../Produce.ral.json";

export const Consume = new ExecutableScript<{
  electricity: HexString;
  num: bigint;
}>(Script.fromJson(ConsumeScriptJson));
export const Produce = new ExecutableScript<{
  electricity: HexString;
  num: bigint;
}>(Script.fromJson(ProduceScriptJson));
